function(tgx_add_example name)
    add_executable(${name}_example ${name}.cpp)
    target_link_libraries(${name}_example PRIVATE tgx::tgx)
    target_compile_options(${name}_example PRIVATE ${TGX_WARNINGS})
endfunction()

tgx_add_example(01_window)
tgx_add_example(02_triangle)
tgx_add_example(03_rectangle)
tgx_add_example(04_circle)
tgx_add_example(05_uniforms)
tgx_add_example(06_blend)
