#!/usr/bin/env python3
"""Bakes a pixel TTF font into src/core/default_font.hpp: the built-in font of tgx.

    python3 tools/bake_font.py thirdparty/unscii/unscii-16.ttf 16 src/core/default_font.hpp

Renders printable ASCII without antialiasing at the font's own pixel size,
one glyph after another in a strip, then a 3x3 white block for shapes, and
writes the strip as bits. Needs Pillow. The font must be drawn on a pixel grid
at that size, its ink inside each glyph's advance and the line.
"""

import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
# Where the font comes from and on what terms, for the generated file.
CREDIT = "unscii-16 by Viznut, public domain: http://viznut.fi/unscii/"

GAP = 1     # transparent columns between glyphs, so none samples its neighbor
WHITE = 3   # the white block's side; shapes sample its middle texel


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    path, size, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]

    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    height = ascent + descent

    glyphs = []
    x = 0
    for code in range(FIRST, LAST + 1):
        advance = font.getlength(chr(code))
        left, top, right, bottom = font.getbbox(chr(code))
        if advance != int(advance) or left < 0 or right > advance or top < 0 or bottom > height:
            sys.exit(f"glyph {chr(code)!r} is off the pixel grid or outside its cell")
        glyphs.append((x, int(advance)))
        x += int(advance) + GAP
    white_x = x
    width = white_x + WHITE

    atlas = Image.new("1", (width, height), 0)
    draw = ImageDraw.Draw(atlas)
    draw.fontmode = "1"
    for code, (gx, _) in zip(range(FIRST, LAST + 1), glyphs):
        draw.text((gx, 0), chr(code), font=font, fill=1)
    draw.rectangle((white_x, 0, white_x + WHITE - 1, WHITE - 1), fill=1)

    row_bytes = (width + 7) // 8
    bits = []
    pixels = atlas.load()
    for y in range(height):
        for byte in range(row_bytes):
            value = 0
            for bit in range(8):
                px = byte * 8 + bit
                if px < width and pixels[px, y]:
                    value |= 0x80 >> bit
            bits.append(value)

    name = font.getname()[0]
    lines = [
        f"// Generated by tools/bake_font.py from {name} at {size} px; do not edit.",
        f"// {CREDIT}",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace tgx::detail::default_font {",
        "    // Glyphs sit on one line this tall, the line spacing too.",
        f"    inline constexpr int line_height = {height};",
        "",
        f"    inline constexpr char first = '{chr(FIRST)}';",
        f"    inline constexpr char last = '{chr(LAST)}';",
        "",
        "    // Where a glyph is in the atlas, and how far it moves the pen: its",
        "    // width. Every glyph is the full line tall.",
        "    struct Glyph {",
        "        std::uint16_t x;",
        "        std::uint8_t width;",
        "    };",
        "",
        "    inline constexpr std::array glyphs{",
    ]
    for code, (gx, w) in zip(range(FIRST, LAST + 1), glyphs):
        shown = {" ": "space", "\\": "backslash"}.get(chr(code), chr(code))
        lines.append(f"        Glyph{{{gx}, {w}}},  // {shown}")
    lines += [
        "    };",
        "    static_assert(glyphs.size() == static_cast<std::size_t>(last - first + 1));",
        "",
        "    // The atlas: the glyphs in a row, then a white block for shapes at",
        "    // (white_x, 0).",
        f"    inline constexpr int atlas_width = {width};",
        f"    inline constexpr int atlas_height = {height};",
        f"    inline constexpr int white_x = {white_x};",
        f"    inline constexpr int white_size = {WHITE};",
        "",
        "    // Its rows top to bottom, a bit per pixel, the leftmost in the most",
        "    // significant bit; each row starts on a whole byte.",
        f"    inline constexpr int row_bytes = {row_bytes};",
        f"    inline constexpr std::array<std::uint8_t, {len(bits)}> bits{{",
    ]
    for start in range(0, len(bits), 16):
        lines.append("        " + " ".join(f"0x{b:02X}," for b in bits[start:start + 16]))
    lines += ["    };", "}", ""]

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
